// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'another-class': string;
  'hello': string;
  'list': string;
  'list-item': string;
}
export const cssExports: CssExports;
export default cssExports;
