export enum Event {
  AXIOS_REQUEST,
  AXIOS_RESPONSE,
  AXIOS_ERROR,
  ERROR_BOUNDARY,
  NO_CONTROLLER_FOUND,
  NO_CONTROLLER_ACTION_FOUND,
  NO_LOCALIZATION_FILE_FOR_REGION_AND_COUNTRY,
  CONTROLLER_NOT_INITIALIZED
}
